name: "cypress test"
on:
  pull_request:
    types: [synchronize]
permissions:
  contents: read
  issues: write
  pull-requests: write
jobs:
  cypress-tests-check:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: ðŸšš Get node
        uses: actions/setup-node@v2
        with:
          node-version: 16.x
      - name: install dependencies
        run: |
          ## Need to unshallow to allow making the version number from
          ## git history.
          git fetch --unshallow --tags &&
          npm install
      - name: ðŸ”¨ Config
        run: |
          rm public/config.sample.json
          export GITHUB_REF_NAME=dev3
          echo "{
            \"appName\": \"Monujo-CI-${GITHUB_REF_NAME}\",
            \"lokapiDb\": \"odoo\",
            \"lokapiHost\": \"${GITHUB_REF_NAME}.lokavaluto.fr\",
            \"mapUrl\": \"https://carte.${GITHUB_REF_NAME}.lokavaluto.fr\",
            \"logoUrl\": \"https://monujo.${GITHUB_REF_NAME}.lokavaluto.fr/img/logo.png\",
            \"loginLogoUrl\": \"https://monujo.${GITHUB_REF_NAME}.lokavaluto.fr/img/logo.png\",
            \"locales\": {
              \"availableLanguages\": {
                \"en-US\": {
                  \"label\": \"English (US)\"
                },
                \"fr-FR\": {
                  \"label\": \"FranÃ§ais (France)\",
                  \"url\": \"https://docker.0k.io/downloads/monujo.fr-FR.json\"
                }
              },
              \"appStringsLanguage\": \"en-US\",
              \"defaultLanguage\": \"en-US\",
              \"preferNavigatorLanguage\": true
            }
          }" > public/config.json
          cat public/config.json
      - name: run server
        run: npm run serve &
      - name: run cypress test
        run: npx cypress run
      - name: Prepare reports
        if: always()
        run: |
          echo "mocha"
          ls cypress/reports/mocha
          npm i -g mochawesome-merge
          npm i -g mochawesome-report-generator
          mochawesome-merge cypress/reports/mocha/*.json -o cypress/reports/mocha/index.json
          marge  --charts=true --showPassed=false --saveJson --reportFilename=report-merge  -o cypress/reports/mocha/ cypress/reports/mocha/index.json
          echo "mocha"
          ls cypress/reports/mocha
      - name: Cypress report
        uses: dmitry/cypress-report-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          pathname: cypress/reports/mocha/report-merge.json
        if: always()
  check-translation:
    needs: cypress-tests-check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          git fetch --unshallow --tags &&
          npm install
          sudo apt-get install gettext
      - name: Check gettext translation/
        run: |
          npm run gettext:extract
      - name: git diff
        run: |
          if [ -n "$(git diff src/i18n/)" ]; then exit 1; fi
